name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Restore .NET Framework packages
        run: nuget restore DiagnosticsVS.sln

      - name: Build
        run: msbuild DiagnosticsVS.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:RunTailwindBuild=true

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: DiagnosticsVS.Adapters/bin/**/*.vsix
